[package]
name = "codemkin"
version = "0.1.0"
authors = ["Nicholas Yang <ny585@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
difference = "2.0"
tokio = { version = "0.2", features = ["full"] }
serde_json = "1.0"